
set(FILES
    Tests/CesiumTest.cpp
    Tests/BoundingRegionTest.cpp
    Tests/OrientedBoundingBoxTest.cpp
    Tests/BoundingSphereTest.cpp
    Tests/MathHelperTest.cpp
    Tests/PlatformInfoTest.cpp
    Tests/BitangentAndTangentGeneratorTest.cpp
    Tests/LoggerSinkTest.cpp
    Tests/GenericIOManagerTest.cpp
    Tests/HttpManagerTest.cpp
    Tests/LocalFileManagerTest.cpp
    Tests/CriticalAssetManagerTest.cpp
    Tests/HttpAssetAccessorTest.cpp
    Tests/GenericAssetAccessorTest.cpp
    Tests/TaskProcessorTest.cpp
    Tests/RenderResourcesPreparerTest.cpp
    Tests/CesiumSystemComponentBusTest.cpp
    Tests/GltfModelComponentBusTest.cpp
    Tests/CesiumTilesetComponentBusTest.cpp
    Tests/CoordinateTransformComponentBusTest.cpp
    Tests/GltfLoadContextTest.cpp
    Tests/GltfPrimitiveBuilderTest.cpp
    Tests/GltfMaterialBuilderTest.cpp
    Tests/GltfModelBuilderTest.cpp
    Tests/GltfModelTest.cpp
    Tests/GeoReferenceTransformComponentTest.cpp
    Tests/CesiumSystemComponentTest.cpp
    Tests/GltfModelComponentTest.cpp
    Tests/CesiumTilesetComponentTest.cpp
)
