
set(FILES
    Include/Cesium/CesiumBus.h
    Source/CesiumModuleInterface.h
    Source/CesiumSystemComponent.cpp
    Source/CesiumSystemComponent.h
    Source/BitangentAndTangentGenerator.cpp
    Source/BitangentAndTangentGenerator.h
    Source/GltfPrimitiveBuilder.cpp
    Source/GltfPrimitiveBuilder.h
    Source/GltfMaterialBuilder.cpp
    Source/GltfMaterialBuilder.h
    Source/GltfModelComponent.cpp
    Source/GltfModelComponent.h
    Source/HttpAssetAccessor.cpp
    Source/HttpAssetAccessor.h
    Source/HttpManager.cpp
    Source/HttpManager.h
)
