
set(FILES
    Tests/CesiumTest.cpp
    Tests/CriticalAssetManagerTest.cpp
    Tests/BitangentAndTangentGeneratorTest.cpp
    Tests/GenericIOManagerTest.cpp
    Tests/HttpManagerTest.cpp
    Tests/LocalFileManagerTest.cpp
    Tests/HttpAssetAccessorTest.cpp
    Tests/TaskProcessorTest.cpp
    Tests/GltfLoadContextTest.cpp
    Tests/GltfPrimitiveBuilderTest.cpp
    Tests/GltfMaterialBuilderTest.cpp
    Tests/GltfModelBuilderTest.cpp
    Tests/GltfModelTest.cpp
    Tests/RenderResourcesPreparerTest.cpp
    Tests/GltfModelComponentTest.cpp
    Tests/CesiumTilesetComponentTest.cpp
)
