
set(FILES
    Source/CesiumEditorSystemComponent.cpp
    Source/CesiumEditorSystemComponent.h
    Source/MatrixWidget.cpp
    Source/MatrixWidget.h
    Source/CesiumIonSession.cpp
    Source/CesiumIonSession.h
    Source/CesiumIonAssetListWidget.cpp
    Source/CesiumIonAssetListWidget.h
    Source/CesiumIonSettingsWidget.cpp
    Source/CesiumIonSettingsWidget.h
    Source/CesiumIonRasterOverlayEditorComponent.cpp
    Source/CesiumIonRasterOverlayEditorComponent.h
    Source/BingRasterOverlayEditorComponent.cpp
    Source/BingRasterOverlayEditorComponent.h
    Source/TMSRasterOverlayEditorComponent.cpp
    Source/TMSRasterOverlayEditorComponent.h
    Source/GeoReferenceCameraFlyControllerEditor.cpp
    Source/GeoReferenceCameraFlyControllerEditor.h
    Source/MathDataWidget.cpp
    Source/MathDataWidget.h
    Source/GeoReferenceTransformEditorComponent.cpp
    Source/GeoReferenceTransformEditorComponent.h
    Source/CesiumTilesetEditorComponent.cpp
    Source/CesiumTilesetEditorComponent.h
    Source/CesiumIonPanelWidget.cpp
    Source/CesiumIonPanelWidget.h
    Source/CesiumResources.qrc
)
