language: cpp
jobs:
  include:
  - stage: Build OS Packages
    name: Windows
    os: windows
    before_install:
    - if [[ $(sfc 2>&1 | tr -d '\0') =~ SCANNOW ]]; then echo Administrator; else echo $USERNAME; fi
    - curl "http://o3debinaries.org/main/Latest/Windows/o3de_installer_2111_2.exe" --output o3de_installer_2111_2.exe
    - md5sum o3de_installer_2111_2.exe
    - ./o3de_installer_2111_2.exe -quiet -layout || echo "Fallback Pass"
    - msiexec -a o3de_21.11.2.msi -quiet -L*V "c:\o3de_installer.log" || echo "Fallback Pass"
    - tail -n200 "c:\o3de_installer.log"
    install:
    - choco install 7zip.portable
    - choco install python --version 3.9.2
    - choco install cmake
    - python -m pip install --upgrade pip
    - pip3 install --upgrade pip
    - pip3 install awscli
    - pip3 install httpie
    before_script:
    - export CESIUM_O3DE_VERSION=$(git describe)
    - export BUILD_CESIUM_O3DE_PACKAGE_NAME=CesiumForO3DE-${TRAVIS_OS_NAME}-${CESIUM_O3DE_VERSION}
    - cd External
    - cmake -B Build -S . -A x64
    script:
    - cmake --build Build --config Release --target install -- /maxcpucount:4
    - cd ..
    - export CLONEDIR=$PWD
    - export LY_PACKAGE_SERVER_URL="file:///$CLONEDIR/External/Packages/Install"
    - ls /c/O3DE
    - ./21.11.2/python/get_python.bat
    - cd /c/O3DE/21.11.2/scripts
    - ./o3de.bat create-project -pp /c/temp/o3de-project
    - ./o3de.bat enable-gem -gp $CLONEDIR -pp /c/temp/o3de-project
    - cd /c/temp/o3de-project
    - cmake --build build -S .
    - cmake --build build --config Release --target INSTALL
    env: PATH=/c/Python39:/c/Python39/Scripts:$PATH
