
set(FILES
    Source/Cesium/PlatformInfo/PlatformInfo.h
    Source/Cesium/PlatformInfo/PlatformInfo.cpp

    Include/Cesium/Math/Cartographic.h
    Source/Cesium/Math/Cartographic.cpp
    Include/Cesium/Math/OrientedBoundingBox.h
    Source/Cesium/Math/OrientedBoundingBox.cpp
    Include/Cesium/Math/BoundingRegion.h
    Source/Cesium/Math/BoundingRegion.cpp
    Include/Cesium/Math/BoundingSphere.h
    Source/Cesium/Math/BoundingSphere.cpp
    Include/Cesium/Math/MathReflect.h
    Source/Cesium/Math/MathReflect.cpp
    Include/Cesium/Math/GeospatialHelper.h
    Source/Cesium/Math/GeospatialHelper.cpp
    Source/Cesium/Math/MathHelper.h
    Source/Cesium/Math/MathHelper.cpp
    Source/Cesium/Math/Interpolator.h
    Source/Cesium/Math/Interpolator.cpp
    Source/Cesium/Math/GeoReferenceInterpolator.h
    Source/Cesium/Math/GeoReferenceInterpolator.cpp
    Source/Cesium/Math/LinearInterpolator.h
    Source/Cesium/Math/LinearInterpolator.cpp

    Source/Cesium/Systems/GenericIOManager.h
    Source/Cesium/Systems/GenericIOManager.cpp
    Source/Cesium/Systems/HttpManager.h
    Source/Cesium/Systems/HttpManager.cpp
    Source/Cesium/Systems/LocalFileManager.h
    Source/Cesium/Systems/LocalFileManager.cpp
    Source/Cesium/Systems/LoggerSink.h
    Source/Cesium/Systems/LoggerSink.cpp
    Source/Cesium/Systems/TaskProcessor.h
    Source/Cesium/Systems/TaskProcessor.cpp
    Source/Cesium/Systems/HttpAssetAccessor.h
    Source/Cesium/Systems/HttpAssetAccessor.cpp
    Source/Cesium/Systems/GenericAssetAccessor.h
    Source/Cesium/Systems/GenericAssetAccessor.cpp
    Source/Cesium/Systems/CriticalAssetManager.h
    Source/Cesium/Systems/CriticalAssetManager.cpp
    Source/Cesium/Systems/CesiumSystem.h
    Source/Cesium/Systems/CesiumSystem.cpp

    Source/Cesium/Gltf/BitangentAndTangentGenerator.h
    Source/Cesium/Gltf/BitangentAndTangentGenerator.cpp
    Source/Cesium/Gltf/GltfLoadContext.h
    Source/Cesium/Gltf/GltfLoadContext.cpp
    Source/Cesium/Gltf/GltfModel.h
    Source/Cesium/Gltf/GltfModel.cpp
    Source/Cesium/Gltf/GltfPrimitiveBuilder.h
    Source/Cesium/Gltf/GltfPrimitiveBuilder.cpp
    Source/Cesium/Gltf/GltfMaterialBuilder.h
    Source/Cesium/Gltf/GltfMaterialBuilder.cpp
    Source/Cesium/Gltf/GltfPBRMaterialBuilder.h
    Source/Cesium/Gltf/GltfPBRMaterialBuilder.cpp
    Source/Cesium/Gltf/GltfModelBuilder.h
    Source/Cesium/Gltf/GltfModelBuilder.cpp

    Source/Cesium/TilesetUtility/GltfRasterMaterialBuilder.h
    Source/Cesium/TilesetUtility/GltfRasterMaterialBuilder.cpp
    Source/Cesium/TilesetUtility/RenderResourcesPreparer.h
    Source/Cesium/TilesetUtility/RenderResourcesPreparer.cpp

    Source/Cesium/EBus/DynamicUiImageComponentBus.h
    Source/Cesium/EBus/DynamicUiImageComponentBus.cpp
    Source/Cesium/EBus/RasterOverlayRequestBus.h
    Source/Cesium/EBus/RasterOverlayRequestBus.cpp
    Include/Cesium/EBus/CoordinateTransformComponentBus.h
    Source/Cesium/EBus/CoordinateTransformComponentBus.cpp
    Include/Cesium/EBus/OriginShiftAwareComponentBus.h
    Source/Cesium/EBus/OriginShiftAwareComponentBus.cpp
    Include/Cesium/EBus/GeoReferenceCameraFlyControllerBus.h
    Source/Cesium/EBus/GeoReferenceCameraFlyControllerBus.cpp
    Include/Cesium/EBus/GltfModelComponentBus.h
    Source/Cesium/EBus/GltfModelComponentBus.cpp
    Include/Cesium/EBus/CesiumTilesetComponentBus.h
    Source/Cesium/EBus/CesiumTilesetComponentBus.cpp

    Source/Cesium/Components/CesiumSystemComponent.h
    Source/Cesium/Components/CesiumSystemComponent.cpp
    Source/Cesium/Components/DynamicUiImageComponent.h
    Source/Cesium/Components/DynamicUiImageComponent.cpp
    Source/Cesium/Components/HtmlUiComponentHelper.h
    Source/Cesium/Components/HtmlUiComponentHelper.cpp
    Include/Cesium/Components/RasterOverlayComponent.h
    Source/Cesium/Components/RasterOverlayComponent.cpp
    Include/Cesium/Components/CesiumIonRasterOverlayComponent.h
    Source/Cesium/Components/CesiumIonRasterOverlayComponent.cpp
    Include/Cesium/Components/BingRasterOverlayComponent.h
    Source/Cesium/Components/BingRasterOverlayComponent.cpp
    Include/Cesium/Components/TMSRasterOverlayComponent.h
    Source/Cesium/Components/TMSRasterOverlayComponent.cpp
    Include/Cesium/Components/GeoReferenceTransformComponent.h
    Source/Cesium/Components/GeoReferenceTransformComponent.cpp
    Include/Cesium/Components/GeoReferenceCameraFlyController.h
    Source/Cesium/Components/GeoReferenceCameraFlyController.cpp
    Include/Cesium/Components/CesiumLevelSettingsComponent.h
    Source/Cesium/Components/CesiumLevelSettingsComponent.cpp
    Include/Cesium/Components/CesiumTilesetCreditComponent.h
    Source/Cesium/Components/CesiumTilesetCreditComponent.cpp
    Include/Cesium/Components/GltfModelComponent.h
    Source/Cesium/Components/GltfModelComponent.cpp
    Include/Cesium/Components/CesiumTilesetComponent.h
    Source/Cesium/Components/CesiumTilesetComponent.cpp
)

